### ISSUE TITLE
Compiling to allow people to run via singularity

### ISSUE THREAD

**Issue by bacaron** [svincibo/app-mergeTCK#4]
I think it would be helpful to compile the matlab code so this app can run on systems that aren't IU HPC. This is what we've been doing with the other apps using matlab code.

See https://github.com/brainlife/app-trekker-roi-tracking/blob/master/compile.sh for an example on how to compile.

Once it's compiled, you'll then need to modify the 'main' file. See https://github.com/brainlife/app-trekker-roi-tracking/blob/master/main for an example on how to run via singularity and what the main file should look like.

**Comment by svincibo** [comment]
done!
